runtime: python38
entrypoint: gunicorn -b :$PORT main:app

instance_class: B1
manual_scaling:
  instances: 1

handlers:
  - url: /slack/events
    secure: always
    script: auto

includes:
  - env_variables.yaml